import {createGraph3D,DEPTH_COLORS} from './graph3D.js';
const $=id=>document.getElementById(id),core=EventAnalysis,query=location.search.slice(1),params=query&&!query.includes('=')?new URLSearchParams({key:decodeURIComponent(query)}):new URLSearchParams(location.search);
const excluded=new Set((params.get('excluded_sources')||'').split(',').filter(Boolean)),fmt=n=>n==null?'—':n.toLocaleString(undefined,{maximumFractionDigits:2}),colors=DEPTH_COLORS;
let data,result,worker,busy=false,pending=false,requestId=0,revision=0,bounds=[0,1],playing=false,playTimer=0,drag=null,selectedSignature=null,selectedHeat=null;
let graphView,selectedNode=null,exactRange=null;const availableSources=new Map();
const status=(message,error=false)=>{$('status').textContent=message;$('status').className=error?'error':''};
function date(ms){return $('utc').checked?new Date(ms).toISOString().replace('T',' ').slice(0,19)+' UTC':new Date(ms).toLocaleString()}
function duration(seconds){return seconds>=86400?fmt(seconds/86400)+' d':seconds>=3600?fmt(seconds/3600)+' h':seconds>=60?fmt(seconds/60)+' min':seconds+' s'}
function values(){const a=Math.min(+$('from').value,+$('to').value),b=Math.max(+$('from').value,+$('to').value),span=bounds[1]-bounds[0];return{a,b,from:exactRange?exactRange[0]:bounds[0]+span*a/10000,to:exactRange?exactRange[1]:bounds[0]+span*b/10000}}
function buildSources(){
 const presets=$('sourcePresets');presets.replaceChildren();const families=[...new Set([...availableSources.keys()].map(core.sourceFamily))].sort();
 for(const family of ['All',...families]){const button=document.createElement('button');button.type='button';button.textContent=family;button.dataset.family=family;button.onclick=()=>{stop();for(const source of availableSources.keys())if(family==='All'||core.sourceFamily(source)===family)excluded.delete(source);else excluded.add(source);syncSources();schedule()};presets.append(button)}
 const box=$('sources');box.replaceChildren();for(const[source,count]of [...availableSources].sort()){const label=document.createElement('label'),input=document.createElement('input');input.type='checkbox';input.dataset.source=source;input.checked=!excluded.has(source);input.onchange=()=>{stop();input.checked?excluded.delete(source):excluded.add(source);syncSources();schedule()};label.append(input,document.createTextNode(' '+(core.sources[source]||source)+' · '+fmt(count)));box.append(label)}syncSources();
}
function syncSources(){
 const included=[...availableSources.keys()].filter(source=>!excluded.has(source));$('sources').querySelectorAll('input').forEach(input=>input.checked=!excluded.has(input.dataset.source));
 $('sourcePresets').querySelectorAll('button').forEach(button=>{const desired=[...availableSources.keys()].filter(source=>button.dataset.family==='All'||core.sourceFamily(source)===button.dataset.family),active=desired.length===included.length&&desired.every(source=>included.includes(source));button.setAttribute('aria-pressed',String(active))});
}
function options(){const v=values();return{from:v.from,to:v.to,excluded:[...excluded],mode:$('decomposition').value,depth:+$('depth').value,maxNodes:16000,powerLevel:+$('powerLevel').value}}
function updateLabels(){const v=values();$('timeLabel').textContent=date(v.from)+' → '+date(v.to);$('startLabel').textContent=date(bounds[0]);$('endLabel').textContent=date(bounds[1]);$('rangeWindow').style.left=v.a/100+'%';$('rangeWindow').style.width=(v.b-v.a)/100+'%';$('depthLabel').textContent=$('depth').value;drawHistogram()}
function schedule(){revision++;pending=true;$('export').disabled=true;$('csv').disabled=true;$('powerCsv').disabled=true;updateLabels();if(worker&&!busy)compute()}
function compute(){if(!worker||!pending)return;busy=true;pending=false;requestId=revision;status('Updating hierarchy and 40 coefficients…');worker.postMessage({type:'compute',id:requestId,options:options()})}
function color(value){const t=Math.max(0,Math.min(1,value));return 'rgb('+[24,44,70].map((v,i)=>Math.round(v+([99,223,201][i]-v)*t)).join(',')+')'}
function drawSignature(){
 const container=$('signature');container.replaceChildren();const labels=['Space D₀','Space D₁','Time D₀','Time D₁'];
 labels.forEach((label,row)=>{const div=document.createElement('div');div.className='signature-row';const title=document.createElement('span');title.textContent=label;div.append(title);for(let i=0;i<10;i++){const index=row*10+i,value=result.coefficients[index],button=document.createElement('button');button.className='signature-cell'+(value==null?' missing':'');button.style.background=color(value/(row<2?2:1));button.textContent=value==null?'—':value.toFixed(1);button.title=`${label} ${i+(row<2?5:22)}→${i+(row<2?6:23)}: ${fmt(value)}`;button.setAttribute('aria-label',button.title);button.onclick=()=>{selectedSignature=index;inspectSignature()};div.append(button)}container.append(div)});inspectSignature();
}
function inspectSignature(){if(selectedSignature==null)return;const row=Math.floor(selectedSignature/10),i=selectedSignature%10,spatial=row<2,level=i+(spatial?5:22),axis=spatial?'H3':'TIX',stats=spatial?result.spatial:result.temporal,a=stats[i],b=stats[i+1],value=result.coefficients[selectedSignature];$('signatureDetail').textContent=`${axis} ${level} → ${level+1} · D${row%2?'₁':'₀'} = ${fmt(value)}. `+(value==null?'Unavailable: empty window or finer than stored precision.':`${fmt(a.n)} → ${fmt(b.n)} occupied bins; growth ×${fmt(b.n/a.n)}; ${fmt(b.mean)} hotspots per fine bin.`)}
function drawHeat(){const box=$('heatmap');box.replaceChildren();const corner=document.createElement('span');corner.textContent='H3 / T';box.append(corner);for(const t of core.TIME){const label=document.createElement('span');label.textContent=t;box.append(label)}const max=Math.max(1,...result.joint.flat().filter(x=>x!=null));core.SPACE.forEach((s,i)=>{const label=document.createElement('span');label.textContent='H'+s;box.append(label);core.TIME.forEach((t,j)=>{const n=result.joint[i][j],button=document.createElement('button');button.className=n==null?'missing':'';button.style.background=color(Math.log1p(n)/Math.log1p(max));button.textContent=n==null?'—':n>=1000?(n/1000).toFixed(1)+'k':n;button.title=`H3 ${s} × TIX ${t}: ${fmt(n)} occupied bins`;button.setAttribute('aria-label',button.title);button.onclick=()=>{selectedHeat=[i,j];inspectHeat()};box.append(button)})});inspectHeat()}
function inspectHeat(){if(!selectedHeat)return;const[i,j]=selectedHeat,n=result.joint[i][j];$('heatDetail').textContent=`H3 ${core.SPACE[i]} × TIX ${core.TIME[j]} (${duration(2**(40-core.TIME[j]))}) · `+(n==null?'Unavailable at stored precision.':`${fmt(n)} occupied pairs · ${fmt(n?result.n/n:0)} hotspots per occupied pair.`)}
function rows(){return ['space','time'].flatMap((axis,a)=>Array.from({length:10},(_,i)=>{const stats=a?result.temporal:result.spatial,coarse=stats[i],fine=stats[i+1],offset=a?20:0;return{axis,from:i+(a?22:5),to:i+(a?23:6),coarse:coarse?.n??null,fine:fine?.n??null,ratio:coarse?.n&&fine?fine.n/coarse.n:null,mean:fine?.mean??null,d0:result.coefficients[offset+i],d1:result.coefficients[offset+10+i]}}))}
function drawTable(){const body=$('coefficientRows');body.replaceChildren();for(const r of rows()){const tr=document.createElement('tr');for(const value of [`${r.axis==='space'?'H':'T'}${r.from}→${r.to}`,`${fmt(r.coarse)}→${fmt(r.fine)}`,r.ratio==null?'—':'×'+fmt(r.ratio),fmt(r.mean),fmt(r.d0),fmt(r.d1)]){const td=document.createElement('td');td.textContent=value;tr.append(td)}body.append(tr)}}
function drawPower(){
 const select=$('powerLevel');if(select.options.length!==result.limits.h3+1){select.replaceChildren();for(let i=0;i<=result.limits.h3;i++){const option=document.createElement('option');option.value=i;option.textContent='H'+i;select.append(option)}}select.value=result.power.level;
 const body=$('powerRows');body.replaceChildren();for(const r of result.power.rows.slice(0,200)){const tr=document.createElement('tr');for(const value of [core.sources[r.source]||r.source,r.cell,fmt(r.detections),fmt(r.observedTimes),fmt(r.meanObservedFrpMW),fmt(r.maxObservedFrpMW)]){const td=document.createElement('td');td.textContent=value;tr.append(td)}body.append(tr)}
 const invalid=result.power.rows.reduce((sum,r)=>sum+r.invalidDetections,0);$('powerSummary').textContent=result.power.rows.length?`${fmt(result.power.rows.length)} satellite / H${result.power.level} pairs. Showing the ${Math.min(200,result.power.rows.length)} highest mean-FRP rows; CSV includes all rows. ${invalid} invalid FRP records excluded.`:'No observations in this selection.';$('powerCsv').disabled=false;
}
function exportPowerCSV(){download(`event-observed-power-${data.key||'sample'}.csv`,['source,H3,H3_level,detections,valid_detections,invalid_detections,observed_times,mean_observed_FRP_MW,max_observed_FRP_MW',...result.power.rows.map(r=>[r.source,r.cell,r.level,r.detections,r.validDetections,r.invalidDetections,r.observedTimes,r.meanObservedFrpMW,r.maxObservedFrpMW].map(x=>x??'').join(','))].join('\n')+'\n','text/csv')}
function drawHistogram(){if(!data)return;const canvas=$('histogram'),dpr=Math.min(2,devicePixelRatio||1),w=canvas.clientWidth,h=canvas.clientHeight;canvas.width=w*dpr;canvas.height=h*dpr;const ctx=canvas.getContext('2d');ctx.scale(dpr,dpr);const n=160,counts=new Uint32Array(n),span=bounds[1]-bounds[0];for(const r of data.records)if(!excluded.has(r.source))counts[Math.min(n-1,Math.max(0,Math.floor((r.time-bounds[0])/span*n)))]++;const max=Math.max(1,...counts),v=values();for(let i=0;i<n;i++){const selected=(i+.5)/n*10000>=v.a&&(i+.5)/n*10000<=v.b;ctx.fillStyle=selected?'#66dfcf':'#2a4055';const height=Math.sqrt(counts[i]/max)*(h-2);ctx.fillRect(i*w/n,h-height,Math.max(1,w/n-1),height)}}
function drawResult(){
 $('spotCount').textContent=fmt(result.n);$('clusterCount').textContent=data.ids.length;const native=result.graph.layers.at(-1);$('jointCount').textContent=fmt(result.joint[Math.min(10,result.limits.h3-5)]?.[Math.min(10,result.limits.tix-22)]??native?.nodes);$('jointScale').textContent=`H${Math.min(15,result.limits.h3)} × T${Math.min(32,result.limits.tix)}`;
 $('validCount').innerHTML=result.coefficients.filter(x=>x!=null).length+' <small>/ 40</small>';$('export').disabled=false;$('csv').disabled=false;$('graphEmpty').hidden=!!result.n;
 drawSignature();drawHeat();drawTable();drawGraph();drawPower();$('satelliteCount').textContent=Object.keys(result.sourceCounts).length+' active';
 const missing=result.coefficients.filter(x=>x==null).length;status(`${fmt(result.n)} hotspots · ${data.ids.length} clusters · stored H${result.limits.h3} / T${result.limits.tix}${missing?' · '+missing+' coefficients unavailable':''}${result.graph.truncated?' · graph branches limited; all records included in statistics':''}`);
}
function drawGraph(){
 const graph=result.graph;$('depth').max=graph.maxDepth;$('depthLabel').textContent=Math.min(+$('depth').value,graph.maxDepth);$('graphStats').textContent=`${fmt(graph.nodes.length)} / ${fmt(graph.fullNodes)} nodes · ${fmt(graph.edges.length)} links${graph.truncated?' · largest branches shown':''}`;
 const levels=$('levels');levels.replaceChildren();for(const layer of graph.layers){const div=document.createElement('div');div.className='level-chip';div.style.borderColor=colors[layer.depth%colors.length];const b=document.createElement('b');b.textContent=fmt(layer.nodes)+' nodes';div.append(b,document.createTextNode(`${layer.h3<0?'Union':'H'+layer.h3} / T${layer.tix}`));levels.append(div)}
 graphView?.update(graph,result.n);
 if(result.n&&!selectedNode)$('inspector').innerHTML='Select a node in the graph.<br><span>Sphere volume encodes hotspot count. Color encodes depth.</span>';
}
function inspectNode(n){selectedNode=n;if(!n){$('inspector').textContent='No selected node in this window.';return}const start=core.bucketTime(n.tick,n.t),stop=start+2**(40-n.t)*1000;$('inspector').replaceChildren();const title=document.createElement('b');title.textContent=`${fmt(n.count)} hotspots · depth ${n.depth}`;const info=document.createElement('div');info.textContent=`${n.cell==='union'?'H3 base-cell union':n.cell+' · H'+n.s} / T${n.t}`;const time=document.createElement('span');time.textContent=date(start)+' → '+date(stop)+' (exclusive)';$('inspector').append(title,info,time)}
function showHover(node,e){$('tooltip').hidden=!node;if(!node)return;const rect=$('graph').getBoundingClientRect();$('tooltip').style.left=Math.min(e.clientX-rect.left+12,rect.width-190)+'px';$('tooltip').style.top=Math.max(15,e.clientY-rect.top-45)+'px';$('tooltip').textContent=`${fmt(node.count)} spots · ${node.s<0?'Union':'H'+node.s} / T${node.t}`}
function download(name,text,type){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function exportJSON(){const v=values();download(`event-signature-${data.key||'sample'}.json`,JSON.stringify({schema:result.schema,createdAt:new Date().toISOString(),key:data.key,eventIds:data.ids,window:{from:new Date(v.from).toISOString(),to:new Date(v.to).toISOString(),inclusive:true},excludedSources:[...excluded],hotspots:result.n,sourceCounts:result.sourceCounts,precision:result.limits,observedPower:result.power,coefficientOrder:['space_D0_H5_to_H15','space_D1_H5_to_H15','time_D0_T22_to_T32','time_D1_T22_to_T32'],coefficients:result.coefficients,valid:result.coefficients.map(x=>x!=null),transitions:rows(),occupancy:result.joint,spatialLevels:core.SPACE,temporalLevels:core.TIME,method:{spatialScale:Math.sqrt(7),temporalScale:2,weight:'hotspot record count',emptyAndUnsupported:null}},null,2),'application/json')}
function exportCSV(){download(`event-signature-${data.key||'sample'}.csv`,['axis,coarse_level,fine_level,coarse_bins,fine_bins,occupancy_ratio,mean_spots_fine,D0,D1',...rows().map(r=>[r.axis,r.from,r.to,r.coarse,r.fine,r.ratio,r.mean,r.d0,r.d1].map(x=>x??'').join(','))].join('\n')+'\n','text/csv')}
function stop(){playing=false;clearTimeout(playTimer);$('play').textContent='▶ Play';$('play').setAttribute('aria-pressed','false')}
function tick(){if(!playing)return;if(busy||pending){playTimer=setTimeout(tick,150);return}let{a,b}=values();const step=100;if(b>=10000){stop();return}if($('playMode').value==='build'){$('to').value=Math.min(10000,b+step)}else{const width=b-a;a=Math.min(10000-width,a+step);$('from').value=a;$('to').value=a+width}schedule();playTimer=setTimeout(tick,250)}
$('play').onclick=()=>{if(playing){stop();return}exactRange=null;let{a,b}=values();if(b>=10000){if($('playMode').value==='build'){$('from').value=0;$('to').value=100}else{const width=b-a>=10000?1500:b-a;$('from').value=0;$('to').value=width}schedule()}playing=true;$('play').textContent='❚❚ Pause';$('play').setAttribute('aria-pressed','true');tick()};
for(const id of ['from','to']){$(id).oninput=()=>{stop();exactRange=null;schedule()};$(id).onpointerdown=stop}
$('full').onclick=()=>{stop();exactRange=null;$('from').value=0;$('to').value=10000;schedule()};$('decomposition').onchange=()=>{stop();schedule()};$('depth').oninput=schedule;$('utc').onchange=()=>{updateLabels();if(result)drawGraph()};$('resetCamera').onclick=()=>graphView?.reset();$('export').onclick=exportJSON;$('csv').onclick=exportCSV;$('powerCsv').onclick=exportPowerCSV;$('powerLevel').onchange=()=>{stop();schedule()};
for(const id of ['help','methodFooter'])$(id).onclick=()=>$('method').showModal();$('closeMethod').onclick=()=>$('method').close();$('method').onclick=e=>{if(e.target===$('method'))$('method').close()};
$('rangeWindow').onpointerdown=e=>{stop();exactRange=null;const v=values();drag={x:e.clientX,a:v.a,b:v.b,id:e.pointerId};e.preventDefault();$('rangeWindow').setPointerCapture(e.pointerId)};$('rangeWindow').onpointermove=e=>{if(!drag||e.pointerId!==drag.id)return;const delta=(e.clientX-drag.x)/$('sliders').clientWidth*10000,a=Math.max(0,Math.min(10000-(drag.b-drag.a),drag.a+delta));$('from').value=Math.round(a);$('to').value=Math.round(a+drag.b-drag.a);schedule()};for(const name of ['onpointerup','onpointercancel'])$('rangeWindow')[name]=()=>drag=null;
addEventListener('resize',drawHistogram);addEventListener('pagehide',()=>{stop();worker?.terminate();graphView?.dispose()});
async function load(){try{
 graphView=createGraph3D({canvas:$('scene'),container:$('graph'),onPick:inspectNode,onHover:showHover,onError:error=>{$('webglError').hidden=false;$('webglError').textContent='3D is unavailable: '+error.message+'. The signature, heatmap and exports remain available.'}});data=await loadAnalysisData(params,status);if(!data.records.length)throw Error('No records loaded');$('identity').textContent=data.key+' · '+(data.sample?'local snapshot':'linked event selection');for(let i=0;i<=15;i++){const option=document.createElement('option');option.value=i;option.textContent='H'+i;$('powerLevel').append(option)}$('powerLevel').value='9';if(!data.sample){$('back').href='event.html?'+data.key;$('sampleLink').hidden=true}
 for(const r of data.records)availableSources.set(r.source,(availableSources.get(r.source)||0)+1);buildSources();

 worker=new Worker('analysis-worker.js');worker.onerror=e=>{status('Analysis worker failed: '+e.message,true);busy=false;stop()};worker.onmessage=({data:message})=>{
  if(message.type==='error'){busy=false;stop();status(message.message,true);return}
  if(message.type==='ready'){
   bounds=[Math.floor(message.first/3600000)*3600000,(Math.floor(message.last/3600000)+1)*3600000];const span=bounds[1]-bounds[0];for(const[id,param,fallback]of [['from','from_ms',0],['to','to_ms',10000]]){const raw=params.get(param),value=raw!==null&&Number.isFinite(+raw)?Math.round((+raw-bounds[0])/span*10000):fallback;$(id).value=Math.max(0,Math.min(10000,value));$(id).disabled=false}const initial=['from_ms','to_ms'].map((key,i)=>params.has(key)&&Number.isFinite(+params.get(key))?Math.max(bounds[0],Math.min(bounds[1],+params.get(key))):bounds[i]);exactRange=initial.sort((a,b)=>a-b);for(const id of ['play','full'])$(id).disabled=false;schedule();return}
  if(message.type==='result'){busy=false;if(message.id===revision){result=message.result;drawResult()}if(pending)compute()}
 };worker.postMessage({type:'init',records:data.records});
 }catch(error){status(error.message,true);$('identity').textContent='Event data could not be loaded.'}}
load();
