const $=id=>document.getElementById(id),rawQuery=location.search.slice(1),compactKey=rawQuery&&!rawQuery.includes('=')?decodeURIComponent(rawQuery):'',params=compactKey?new URLSearchParams():new URLSearchParams(location.search),geoParams=['only','exclude'],eventKeys=['id','geo_only','geo_exclude','events','search','ev_lng','ev_lat','ev_z','ev_bearing','ev_pitch','ev_tf','ev_tt','basemap','nearby','nearby_sort','progression','progression_method','cover','show_hotspots','color_instrument','local_time','show_progression','color_frp','isochrones'],canvas=$('chart'),ctx=canvas.getContext('2d');let primaryId=params.get('id'),database=params.get('db')||'ARCH',canonicalKey='',records=[],start=0,end=0,bins=[],anchorLng=0,primaryH5='',nearbyEvents=[],searchH5=new Set(),progressionActive=false,progressionMethod='astar',progressionPreference=true,frpColorPreference=true,isochronePreference=false,progressionMaxFrp=0,progressionMaxArea=0,progressionArea=[],viirsArea=[],viirsMaxArea=0,progressionCells=[],isochronesReady=false,isochroneGeneration=0,coverActive=false,coverGeneration=0,progressionPopupAttached=false,clusterRegion='Region',clusterDateTitle='';const selectedEvents=new Map(),eventColors=new Map();$('showHotspots').checked=true;$('colorInstrument').checked=false;$('localTime').checked=true;$('timeCaption').textContent='Local Start - Local End';
const progressionControl=document.createElement('select');progressionControl.id='progressionAction';progressionControl.setAttribute('aria-label','Progression algorithm');progressionControl.innerHTML='<option value="">Estimate progression…</option><option value="wavefront">Wavefront</option><option value="wavecover">Wavecover</option><option value="astar">A* constrained</option><option value="clear">Clear progression</option>';$('estimateProgression').replaceWith(progressionControl);const coverButton=document.createElement('button');coverButton.id='coverButton';coverButton.textContent='Cover';progressionControl.before(coverButton);
const withContext=q=>{q.set('db',database);geoParams.forEach(k=>{const v=params.get('geo_'+k)||params.get(k);if(v)q.set(k,v)});return q},eventPage=id=>{const q=new URLSearchParams(params);q.set('id',id);q.delete('events');return'event.html?'+q},binary=async q=>{const r=await fetch('stfyhotspot.php?'+withContext(q));if(!r.ok)throw Error(`HTTP ${r.status}`);return r.arrayBuffer()};
const instruments={E:'GOESE',W:'GOESW',H:'HMWR',M:'MODIS',F:'MTGLSA','1':'VIIRSJ1V','2':'VIIRSJ2V',S:'VIIRSSNP'};let fluxObservations={points:[],peakByCell:new Map(),nominal:0,invalid:0},fluxBins=[],rosPoints=[];let fullTimeRange=null,focusTimeRange=null;
async function eventList(q){const b=await binary(q),v=new DataView(b);if(b.byteLength<16||String.fromCharCode(...new Uint8Array(b,0,4))!=='ELS1'||v.getUint8(4)!==1)throw Error('Invalid ELS1 list');const count=v.getUint32(8,true),stringBytes=v.getUint32(12,true),tableEnd=16+count*56;if(b.byteLength!==tableEnd+stringBytes)throw Error('Truncated ELS1 list');const decoder=new TextDecoder(),events=[];for(let i=0,o=16;i<count;i++,o+=56){const flags=v.getUint32(o+40,true),so=v.getUint32(o+44,true),sl=v.getUint32(o+48,true);if(so+sl>stringBytes)throw Error('Invalid ELS1 string');events.push({id:decoder.decode(new Uint8Array(b,tableEnd+so,sl)),kind:flags&1?'ARCHIVE':'LIVE',industrial:!!(flags&2),h7:v.getBigUint64(o,true).toString(16).padStart(15,'0'),first:v.getBigUint64(o+8,true).toString(16),last:v.getBigUint64(o+16,true).toString(16),hotspots:Number(v.getBigUint64(o+24,true)),frp:v.getFloat64(o+32,true)})}return events}
async function eventData(eventId){const b=await binary(new URLSearchParams({api:'event',id:eventId}));if(b.byteLength%24)throw Error('Truncated FRP1R event');const v=new DataView(b),records=[];for(let o=0;o<b.byteLength;o+=24){const source=String.fromCharCode(v.getUint8(o+21)),frp=v.getFloat32(o+16,true);records.push({h3:v.getBigUint64(o,false).toString(16).padStart(15,'0'),tix:v.getBigUint64(o+8,false).toString(16),frp,density:EventMetrics.fluxDensity({frp,source}),confidence:v.getUint8(o+20),source,flags:v.getUint16(o+22,false)})}const split=eventId.indexOf(':');return{id:eventId,kind:eventId.slice(0,split),relative:eventId.slice(split+1),records}}
const back=new URLSearchParams(params);eventKeys.forEach(k=>back.delete(k));['tf','tt','h5','all','latest','active'].forEach(k=>back.delete(k));back.set('active','1');const backButton=document.querySelector('.back');backButton.href='index.html?'+back;
const map=new maplibregl.Map({container:'map',center:[+(params.get('ev_lng')||9),+(params.get('ev_lat')||43)],zoom:+(params.get('ev_z')||5),bearing:+(params.get('ev_bearing')||0),pitch:+(params.get('ev_pitch')||0),style:{version:8,sources:{base:{type:'raster',tiles:['https://tile.openstreetmap.org/{z}/{x}/{y}.png'],tileSize:256,attribution:'© OpenStreetMap'},satellite:{type:'raster',tiles:['https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}'],tileSize:256,attribution:'Tiles © Esri'}},layers:[{id:'base',type:'raster',source:'base',layout:{visibility:(params.get('basemap')||'satellite')==='map'?'visible':'none'},paint:{'raster-saturation':-.45,'raster-brightness-max':.72}},{id:'satellite',type:'raster',source:'satellite',layout:{visibility:(params.get('basemap')||'satellite')==='map'?'none':'visible'},paint:{'raster-brightness-max':.82}}]}});map.addControl(new maplibregl.NavigationControl(),'bottom-right');$('basemap').value=params.get('basemap')||'satellite';$('nearbySort').value=params.get('nearby_sort')||'latest';
function progressionPopup(e){if($('colorFrp').checked)return;const p=e.features[0].properties;new maplibregl.Popup().setLngLat(e.lngLat).setHTML(`<b>${p.original?'Original hotspot H9':'Interpolated H9'}</b><br>${stamp(+p.time)}<br>${(+p.frp).toFixed(3)} kW·m⁻²${p.original?` · ${p.count} hotspots`:''}`).addTo(map)}
const mapReady=new Promise(resolve=>map.once('load',()=>{map.addSource('progression',{type:'geojson',data:{type:'FeatureCollection',features:[]}});map.addLayer({id:'progressionFill',type:'fill',source:'progression',layout:{visibility:'none'},paint:{'fill-color':['interpolate',['linear'],['get','timeNorm'],0,'#315efb',.45,'#17c3b2',.72,'#ffe066',1,'#ef233c'],'fill-opacity':['case',['==',['get','original'],1],.68,.38]}});map.addLayer({id:'progressionLine',type:'line',source:'progression',layout:{visibility:'none'},paint:{'line-color':['case',['==',['get','original'],1],'#ffffff','#aeb5bd'],'line-opacity':.8,'line-width':['case',['==',['get','original'],1],1.4,.65]}});map.addSource('isochrones',{type:'geojson',data:{type:'FeatureCollection',features:[]}});map.addLayer({id:'isochroneLines',type:'line',source:'isochrones',layout:{visibility:'none','line-cap':'round','line-join':'round'},paint:{'line-color':['interpolate',['linear'],['get','timeNorm'],0,'#315efb',.45,'#17c3b2',.72,'#ffe066',1,'#ef233c'],'line-opacity':.82,'line-width':2.2}});map.addSource('searchArea',{type:'geojson',data:{type:'FeatureCollection',features:[]}});map.addLayer({id:'searchArea',type:'fill',source:'searchArea',paint:{'fill-color':'#8ed8ff','fill-opacity':.2,'fill-antialias':false}});map.addSource('spots',{type:'geojson',data:{type:'FeatureCollection',features:[]}});map.addLayer({id:'spots',type:'circle',source:'spots',layout:{visibility:'visible'},paint:{'circle-radius':5,'circle-color':['get','color'],'circle-opacity':.86,'circle-stroke-color':'#fff8','circle-stroke-width':1}});map.addSource('historyEvents',{type:'geojson',data:{type:'FeatureCollection',features:[]}});map.addLayer({id:'historyEvents',type:'fill',source:'historyEvents',paint:{'fill-color':['get','color'],'fill-opacity':.95,'fill-outline-color':'#ffffff'}});map.addSource('historySelected',{type:'geojson',data:{type:'FeatureCollection',features:[]}});map.addLayer({id:'historySelected',type:'circle',source:'historySelected',paint:{'circle-radius':5,'circle-color':['get','color'],'circle-opacity':.9,'circle-stroke-color':'#ffffffaa','circle-stroke-width':1}});map.on('click','progressionFill',progressionPopup);progressionPopupAttached=true;resolve()}));
const latestLayerReady=mapReady.then(()=>{const marker=document.createElement('canvas'),markerContext=marker.getContext('2d');marker.width=marker.height=32;markerContext.strokeStyle='#ffffff';markerContext.lineWidth=7;markerContext.lineCap='round';markerContext.beginPath();markerContext.moveTo(7,7);markerContext.lineTo(25,25);markerContext.moveTo(25,7);markerContext.lineTo(7,25);markerContext.stroke();markerContext.strokeStyle='#ff3b30';markerContext.lineWidth=3;markerContext.beginPath();markerContext.moveTo(7,7);markerContext.lineTo(25,25);markerContext.moveTo(25,7);markerContext.lineTo(7,25);markerContext.stroke();map.addImage('latest-cross',markerContext.getImageData(0,0,32,32));map.addSource('latestSpots',{type:'geojson',data:{type:'FeatureCollection',features:[]}});map.addLayer({id:'latestSpots',type:'symbol',source:'latestSpots',layout:{'icon-image':'latest-cross','icon-size':.72,'icon-allow-overlap':true,'icon-ignore-placement':true}})});
const coverReady=mapReady.then(()=>{map.addSource('landcover',{type:'geojson',data:{type:'FeatureCollection',features:[]}});map.addLayer({id:'landcoverFill',type:'fill',source:'landcover',paint:{'fill-color':['match',['get','class'],1,'#166b35',2,'#b99a39',3,'#91bd4b',4,'#c790c8',5,'#d84d43',6,'#a99f8c',7,'#e8eef2',8,'#397db6',9,'#42a9a3',10,'#2d9367',11,'#b7b36b','#777777'],'fill-opacity':['case',['boolean',['get','vegetation'],false],.46,.25]}},'progressionFill');map.addLayer({id:'landcoverLine',type:'line',source:'landcover',paint:{'line-color':'#d7e1e7','line-opacity':.5,'line-width':.6}},'progressionFill');map.on('click','landcoverFill',e=>{const p=e.features[0].properties;new maplibregl.Popup().setLngLat(e.lngLat).setHTML(`<b>${p.level} ${p.cell}</b><br>${p.className}<br>${p.state}${p.vegetation?' · vegetation':''}`).addTo(map)})});
const tixEpoch=v=>{const x=BigInt('0x'+v),l=Number(x>>42n),p=(x&((1n<<42n)-1n))>>BigInt(42-l);return Number(p*(1n<<BigInt(40-l))-549755813888n)*1000},utcStamp=t=>new Date(t).toISOString().replace('.000',''),two=n=>String(n).padStart(2,'0'),localStamp=t=>{const d=new Date(t),offset=-d.getTimezoneOffset(),sign=offset>=0?'+':'-',fraction=d.getMilliseconds()?'.'+String(d.getMilliseconds()).padStart(3,'0'):'';return`${d.getFullYear()}-${two(d.getMonth()+1)}-${two(d.getDate())}T${two(d.getHours())}:${two(d.getMinutes())}:${two(d.getSeconds())}${fraction}${sign}${two(Math.floor(Math.abs(offset)/60))}:${two(Math.abs(offset)%60)}`},stamp=t=>$('localTime').checked?localStamp(t):utcStamp(t);
const titleLine=document.createElement('div'),latestIndexed=document.createElement('span'),latestCrossMaxAge=18*60*60*1000;titleLine.className='title-line';latestIndexed.id='latestIndexed';latestIndexed.className='latest-indexed';latestIndexed.textContent='Latest (× points): loading…';$('title').before(titleLine);titleLine.append($('title'),latestIndexed);let latestIndexedTime=0;
const latestLocalDateTime=time=>{const d=new Date(time);return`${d.getFullYear()}-${two(d.getMonth()+1)}-${two(d.getDate())} ${two(d.getHours())}:${two(d.getMinutes())}:${two(d.getSeconds())}`};
function renderLatestIndexed(){if(!latestIndexedTime)return;const recent=Date.now()-latestIndexedTime<latestCrossMaxAge;latestIndexed.hidden=!recent;if(!recent)map.getSource('latestSpots')?.setData({type:'FeatureCollection',features:[]});else{const minutes=Math.max(0,Math.floor((Date.now()-latestIndexedTime)/60000));latestIndexed.textContent=`Latest (× points) ${latestLocalDateTime(latestIndexedTime)} · ${minutes.toLocaleString()} minute${minutes===1?'':'s'} ago`}}
async function loadLatestIndexed(){}
const selectionTime=t=>{const d=new Date(t);return`${d.getFullYear()}-${two(d.getMonth()+1)}-${two(d.getDate())} <b>${two(d.getHours())}:${two(d.getMinutes())}</b>`},selectionZone=t=>{const minutes=-new Date(t).getTimezoneOffset(),sign=minutes>=0?'+':'-',absolute=Math.abs(minutes),tail=absolute%60?':'+two(absolute%60):'';return`(UTC${sign}${Math.floor(absolute/60)}${tail})`};
function titleDate(t){const d=new Date(t);return`${two(d.getDate())}-${two(d.getMonth()+1)}-${d.getFullYear()}`}
function setClusterTitle(region=clusterRegion){clusterRegion=region||'Region';const full=`Fire Cluster - ${clusterDateTitle||'--'} - ${clusterRegion}`;document.title=full;$('title').textContent='Fire Cluster';$('subtitle').textContent=`${clusterDateTitle||'--'} · ${clusterRegion}`}
function eventCenter(event){const coords=event.records.map(r=>h3.cellToLatLng(r.h3)),lat=coords.reduce((s,c)=>s+c[0],0)/coords.length,lng=coords.reduce((s,c)=>s+unwrap(c[1]),0)/coords.length;return{lat,lng}}
async function inferRegionName(lat,lng){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),3000);try{const q=new URLSearchParams({format:'jsonv2',lat:String(lat),lon:String(lng),zoom:'8',addressdetails:'1','accept-language':'en'}),r=await fetch('https://nominatim.openstreetmap.org/reverse?'+q,{signal:controller.signal}),d=await r.json(),a=d.address||{};if(a.country_code==='us')return a.state||a.county||a.country||'Region';return a.county||a.state_district||a.state||a.region||a.province||a.country||'Region'}finally{clearTimeout(timer)}}
const tixL23=v=>BigInt(Math.floor((tixEpoch(v)/1000+549755813888)/131072));
const instrumentColors={E:'#ff3b30',W:'#ff9500',H:'#ffcc00',M:'#34c759',F:'#00c7be','1':'#007aff','2':'#5856d6',S:'#af52de'};
const colorFor=id=>{if(!eventColors.has(id)){let h=2166136261;for(let i=0;i<id.length;i++)h=Math.imul(h^id.charCodeAt(i),16777619);eventColors.set(id,`hsl(${(h>>>0)%360} 78% 57%)`)}return eventColors.get(id)};
function selected(){let a=+$('from').value,b=+$('to').value;if(a>b)[a,b]=[b,a];return[start+(end-start)*a/10000,start+(end-start)*b/10000]}
function updateFocusButton(){const [a,b]=selected(),focused=!!focusTimeRange,button=$('timelineFocus');button.disabled=!focused&&(!records.length||b<=a||(a===start&&b===end));button.setAttribute('aria-pressed',String(focused));const label=focused?'Restore full event time range':'Focus selected time window';button.setAttribute('aria-label',label);button.title=label;$('focusArrows').setAttribute('d',focused?'M7 8H2m3-3-3 3 3 3M13 8h5m-3-3 3 3-3 3':'M2 8h5m-3-3 3 3-3 3M18 8h-5m3-3-3 3 3 3')}
// Rebin only observations inside the focused domain; keep full-event reconstruction history.
function refreshTimelineBins(){const n=Math.min(240,Math.max(24,Math.ceil((end-start)/EventMetrics.COOBSERVATION_MS)));bins=[{values:Array(n).fill(0)}];const flux=focusTimeRange?EventMetrics.localFlux(records.filter(r=>r.time>=start&&r.time<=end),h3):fluxObservations;fluxBins=EventMetrics.binFlux(flux,start,end,n)}
function toggleTimeFocus(){stopPlayback();if(focusTimeRange){focusTimeRange=null;[start,end]=fullTimeRange}else{const [a,b]=selected();if(!records.length||b<=a||(a===start&&b===end))return;focusTimeRange=[a,b];start=a;end=b}$('from').value=0;$('to').value=10000;refreshTimelineBins();buildTimeSlots();update();if(!$('nearby').hidden)updateHistoryLayers()}
function windowArea(points){if(!focusTimeRange)return points;let area=0;const sliced=[];for(const p of points){if(p.time<=start)area=p.area;else if(p.time<=end)sliced.push(p);else break}const result=[{time:start,area},...sliced];result.push({time:end,area:result.at(-1).area});return result}
function updateRangeWindow(){let a=+$('from').value,b=+$('to').value;if(a>b)[a,b]=[b,a];$('rangeWindow').style.left=a/100+'%';$('rangeWindow').style.width=(b-a)/100+'%'}
const frpColors=['#000000','#5b0000','#b30000','#ff1a00','#ff7300','#ffcc00','#ffffff'];
const infernoColor=t=>{const p=Math.max(0,Math.min(1,t))*(frpColors.length-1),i=Math.min(frpColors.length-2,Math.floor(p)),f=p-i,a=parseInt(frpColors[i].slice(1),16),b=parseInt(frpColors[i+1].slice(1),16),channel=s=>Math.round(((a>>s)&255)*(1-f)+((b>>s)&255)*f);return`rgb(${channel(16)} ${channel(8)} ${channel(0)})`};
function updateProgressionTime(a,b){if(!map.getLayer('progressionFill'))return;const frp=$('colorFrp').checked,filter=focusTimeRange?['all',['>=',['get','time'],start],['<=',['get','time'],b]]:['<=',['get','time'],b],scale=frp?['interpolate',['linear'],['get','frpNorm'],0,frpColors[0],.1667,frpColors[1],.3333,frpColors[2],.5,frpColors[3],.6667,frpColors[4],.8333,frpColors[5],1,frpColors[6]]:['interpolate',['linear'],['get','timeNorm'],0,'#315efb',.45,'#17c3b2',.72,'#ffe066',1,'#ef233c'],before=['<',['get','time'],a],color=['case',before,'#000000',scale],normalOpacity=['case',['==',['get','original'],1],.68,.38],energyOpacity=['interpolate',['linear'],['get','frpNorm'],0,.5,1,.9];map.setFilter('progressionFill',filter);map.setFilter('progressionLine',filter);map.setPaintProperty('progressionFill','fill-color',color);map.setPaintProperty('progressionFill','fill-opacity',['case',before,.65,frp?energyOpacity:normalOpacity]);map.setPaintProperty('progressionFill','fill-antialias',!frp);map.setPaintProperty('progressionLine','line-color',['case',before,'#000000',['==',['get','original'],1],'#ffffff','#aeb5bd']);map.setLayoutProperty('progressionLine','visibility',progressionPreference&&!frp?'visible':'none');updateIsochroneTime(a,b);if(frp&&progressionPopupAttached){map.off('click','progressionFill',progressionPopup);progressionPopupAttached=false}else if(!frp&&!progressionPopupAttached){map.on('click','progressionFill',progressionPopup);progressionPopupAttached=true}}

// Optional isochrone overlay; it reads progression output but does not modify it.
const contourVertex=p=>p[0].toFixed(7)+','+p[1].toFixed(7);
function addContourCell(edges,cell){const ring=h3.cellToBoundary(cell,true).map(p=>[unwrap(p[0]),p[1]]);for(let i=0;i<ring.length;i++){const a=ring[i],b=ring[(i+1)%ring.length],ak=contourVertex(a),bk=contourVertex(b),key=ak<bk?ak+'|'+bk:bk+'|'+ak;if(edges.has(key))edges.delete(key);else edges.set(key,{a,b,ak,bk})}}
function smoothContour(points){if(points.length<5)return points;let open=points.slice(0,-1);for(let pass=0;pass<2;pass++){const next=[];for(let i=0;i<open.length;i++){const a=open[i],b=open[(i+1)%open.length];next.push([a[0]*.75+b[0]*.25,a[1]*.75+b[1]*.25],[a[0]*.25+b[0]*.75,a[1]*.25+b[1]*.75])}open=next}return[...open,open[0]]}
function contourLines(edges){const list=[...edges.values()],adj=new Map(),unused=new Set(list.map((_,i)=>i));list.forEach((e,i)=>{for(const key of[e.ak,e.bk]){if(!adj.has(key))adj.set(key,[]);adj.get(key).push(i)}});const lines=[];while(unused.size){const first=unused.values().next().value,e=list[first];unused.delete(first);const points=[e.a,e.b];let key=e.bk,guard=0;while(key!==e.ak&&guard++<=list.length){const next=(adj.get(key)||[]).find(i=>unused.has(i));if(next===undefined)break;unused.delete(next);const edge=list[next],forward=edge.ak===key;points.push(forward?edge.b:edge.a);key=forward?edge.bk:edge.ak}if(points.length>3&&key===e.ak)lines.push(smoothContour(points))}return lines}
function updateIsochroneTime(a,b){if(!map.getLayer('isochroneLines'))return;map.setFilter('isochroneLines',focusTimeRange?['all',['>=',['get','time'],start],['<=',['get','time'],b]]:['<=',['get','time'],b]);map.setPaintProperty('isochroneLines','line-color',['case',['<',['get','time'],a],'#000000',['interpolate',['linear'],['get','timeNorm'],0,'#315efb',.45,'#17c3b2',.72,'#ffe066',1,'#ef233c']])}
async function buildIsochrones(){if(isochronesReady||!progressionCells.length)return;const run=++isochroneGeneration,ordered=[...progressionCells].sort((a,b)=>a[1].time-b[1].time),t0=ordered[0][1].time,t1=ordered[ordered.length-1][1].time,span=Math.max(1,t1-t0),edges=new Map(),features=[];let cursor=0;for(let level=1;level<=24;level++){const time=t0+span*level/24;while(cursor<ordered.length&&ordered[cursor][1].time<=time)addContourCell(edges,ordered[cursor++][0]);const lines=contourLines(edges);if(lines.length)features.push({type:'Feature',geometry:{type:'MultiLineString',coordinates:lines},properties:{time,timeNorm:(time-t0)/span}});if(level%4===0){await new Promise(requestAnimationFrame);if(run!==isochroneGeneration)return}}map.getSource('isochrones').setData({type:'FeatureCollection',features});isochronesReady=true;map.setLayoutProperty('isochroneLines','visibility',$('showIsochrones').checked?'visible':'none');updateIsochroneTime(...selected())}
function clearIsochrones(){isochroneGeneration++;isochronesReady=false;progressionCells=[];if($('downloadBmap'))$('downloadBmap').disabled=true;$('showIsochrones').checked=false;$('showIsochrones').disabled=true;map.getSource('isochrones')?.setData({type:'FeatureCollection',features:[]});map.getLayer('isochroneLines')&&map.setLayoutProperty('isochroneLines','visibility','none')}
const unwrap=lng=>{while(lng-anchorLng>180)lng-=360;while(lng-anchorLng<-180)lng+=360;return lng};
const coverClassNames={0:'Invalid',1:'Tree cover',2:'Shrubland',3:'Grassland',4:'Cropland',5:'Built-up',6:'Bare / sparse',7:'Snow / ice',8:'Permanent water',9:'Herbaceous wetland',10:'Mangroves',11:'Moss / lichen'},vegetationClasses=new Set([1,2,3,4,9,10,11]),coverBase='./';
const progressionCoverClasses=new Map();
function coverFeature(cell,level,cls,vegetation,state){const ring=h3.cellToBoundary(cell,true).map(p=>[unwrap(p[0]),p[1]]);ring.push(ring[0]);return{type:'Feature',geometry:{type:'Polygon',coordinates:[ring]},properties:{cell,level,class:cls,className:coverClassNames[cls]||'Unknown',vegetation,state}}}
function clearCover(){coverGeneration++;coverActive=false;map.getSource('landcover')?.setData({type:'FeatureCollection',features:[]});$('coverButton').textContent='Cover'}
async function concurrentMap(items,limit,worker){let cursor=0;await Promise.all(Array.from({length:Math.min(limit,items.length)},async()=>{while(cursor<items.length)await worker(items[cursor++])}))}
async function loadCoverMetadata(){await coverReady;if(coverActive){clearCover();return}if(!records.length)return;const run=++coverGeneration,h5s=[...new Set(records.map(r=>h3.cellToParent(r.h3,5)))],features=[];$('coverButton').disabled=true;$('progressionStatus').hidden=false;$('progressionStatus').textContent=`Loading ${h5s.length.toLocaleString()} H5 cover summaries…`;try{await concurrentMap(h5s,6,async h5=>{const r=await fetch(coverBase+'h3vdbinfo.php?'+h5),d=await r.json();if(!r.ok||d.error)throw Error(d.error||`HTTP ${r.status}`);const children=d.h7_children||h3.cellToChildren(h5,7).map(h7=>({h7,state:'constant',contains_vegetation:d.contains_vegetation,majority:d.summary}));for(const child of children){const value=child.majority||d.summary||{};features.push(coverFeature(child.h7,'H7',value.class_id||0,!!child.contains_vegetation,child.state||d.state||'constant'))}});if(run!==coverGeneration)return;map.getSource('landcover').setData({type:'FeatureCollection',features});coverActive=true;$('coverButton').textContent='Hide cover';$('progressionStatus').textContent=`Cover · ${h5s.length.toLocaleString()} H5 · ${features.length.toLocaleString()} L7 summaries · no chunks read`}catch(e){if(run===coverGeneration)$('progressionStatus').textContent='Cover error: '+e.message}finally{if(run===coverGeneration)$('coverButton').disabled=false}}
function parseCoverChunks(buffer){const v=new DataView(buffer);if(buffer.byteLength<16||new TextDecoder().decode(new Uint8Array(buffer,0,5))!=='H7VC1'||v.getUint32(8,true)!==1)throw Error('Invalid H7VC1 cover response');const count=v.getUint32(12,true),entries=[];if(buffer.byteLength<16+count*48)throw Error('Truncated H7VC1 cover response');for(let i=0,o=16;i<count;i++,o+=48)entries.push({h7:v.getBigUint64(o,true).toString(16).padStart(15,'0'),codec:v.getUint8(o+9),value:v.getUint8(o+10),flags:v.getUint16(o+14,true),valid:v.getUint32(o+24,true),uncompressed:v.getUint32(o+28,true),compressed:v.getUint32(o+32,true),offset:Number(v.getBigUint64(o+40,true))});return{buffer,entries}}
function coverOrdinalH9(cell){const x=BigInt('0x'+cell),digit=r=>Number((x>>BigInt(3*(15-r)))&7n);return digit(8)*7+digit(9)}
function coverH9Summary(bytes,ordinal){const begin=ordinal*2401,end=Math.min(bytes.length,begin+2401),counts=new Uint32Array(16);let valid=0,veg=0;for(let i=begin;i<end;i++){const value=bytes[i];if(value&128)continue;valid++;counts[value&15]++;if(value&16)veg++}let cls=0;for(let i=1;i<16;i++)if(counts[i]>counts[cls])cls=i;return{cls,valid,veg}}
async function loadWaveCover(original,run,status,display=true){await coverReady;const h7s=new Set();for(const h9 of original.keys()){const h7=h3.cellToParent(h9,7);for(const cell of h3.gridDisk(h7,1))h7s.add(cell)}const list=[...h7s],allowed=new Set(),features=[];let loaded=0;for(let begin=0;begin<list.length;begin+=96){if(run!==progressionGeneration)return null;const batch=list.slice(begin,begin+96),r=await fetch(coverBase+'h3vdcover.php?h7='+batch.join(','));if(!r.ok){const d=await r.json();throw Error(d.error||`HTTP ${r.status}`)}const packed=parseCoverChunks(await r.arrayBuffer());if(run!==progressionGeneration)return null;for(const entry of packed.entries){let dense=null;if(entry.compressed){const source=new Uint8Array(packed.buffer,entry.offset,entry.compressed);dense=entry.codec===2?fzstd.decompress(source):new Uint8Array(source);if(dense.length!==entry.uncompressed)throw Error('Unexpected WorldCover chunk size')}for(const h9 of h3.cellToChildren(entry.h7,9)){const summary=dense?coverH9Summary(dense,coverOrdinalH9(h9)):{cls:entry.value&15,valid:entry.valid?2401:0,veg:entry.flags&16?2401:0},fraction=summary.valid?summary.veg/summary.valid:0;progressionCoverClasses.set(h9,summary.valid?EventBmap.worldCoverCode(summary.cls):0);if(summary.valid&&vegetationClasses.has(summary.cls)&&fraction>=.1){allowed.add(h9);if(display)features.push(coverFeature(h9,'H9',summary.cls,true,'vegetation mask'))}}}loaded+=batch.length;status.textContent=`Vegetation mask · decoded ${loaded.toLocaleString()} / ${list.length.toLocaleString()} H7 chunks`;await new Promise(requestAnimationFrame)}if(display){map.getSource('landcover').setData({type:'FeatureCollection',features});coverActive=true;$('coverButton').textContent='Hide cover'}return allowed}
function makeBins(){fluxObservations=EventMetrics.localFlux(records,h3);refreshTimelineBins()}
function slotStep(){const duration=end-start;return duration<3600000?Math.max(60000,Math.ceil(duration/6/60000)*60000):duration<21600000?600000:duration<86400000?3600000:duration<259200000?10800000:duration<864000000?43200000:86400000}
function buildTimeSlots(){const step=slotStep(),long=end-start>=259200000,container=$('timeSlots');container.innerHTML='';for(let t=start;t<end;t+=step){const d=new Date(t),button=document.createElement('button');button.className='time-slot';button.textContent=(long?two(d.getDate())+' ':'')+two(d.getHours())+(step<3600000?':'+two(d.getMinutes()):'h');button.title=`${localStamp(t)} to ${localStamp(Math.min(end,t+step))}`;button.onclick=()=>{const span=end-start;$('from').value=Math.round((t-start)/span*10000);$('to').value=Math.round((Math.min(end,t+step)-start)/span*10000);update()};container.append(button)}}
let progressionGeneration=0,progressionRunning=false;
function clearProgression(){progressionGeneration++;progressionRunning=false;progressionActive=false;progressionMaxFrp=0;progressionMaxArea=0;progressionArea=[];viirsArea=[];viirsMaxArea=0;rosPoints=[];clearIsochrones();map.getSource('progression')?.setData({type:'FeatureCollection',features:[]});for(const layer of['progressionFill','progressionLine'])if(map.getLayer(layer))map.setLayoutProperty(layer,'visibility','none');$('showProgression').checked=false;$('showProgression').disabled=true;$('colorFrp').checked=false;$('colorFrp').disabled=true;$('progressionStatus').hidden=true;$('progressionAction').disabled=false;$('progressionAction').value='';if(records.length)update()}
function progressionDensityMode(){return progressionActive&&$('showProgression').checked}
const excludedSources=new Set();
const satelliteNames={F:'MTG',M:'MODIS',S:'VIIRS Suomi NPP','1':'VIIRS NOAA-20','2':'VIIRS NOAA-21',E:'GOES East',W:'GOES West',H:'Himawari'};
function renderSatelliteMenu(allRecords){
 const counts=new Map();for(const r of allRecords)counts.set(r.source,(counts.get(r.source)||0)+1);
 const menu=$('satelliteMenu');menu.replaceChildren();$('satelliteToggle').disabled=!counts.size;
 for(const [source,count] of [...counts].sort((a,b)=>(satelliteNames[a[0]]||a[0]).localeCompare(satelliteNames[b[0]]||b[0]))){
  const label=document.createElement('label'),input=document.createElement('input'),name=document.createElement('span'),total=document.createElement('small');
  input.type='checkbox';input.checked=!excludedSources.has(source);input.dataset.source=source;name.textContent=satelliteNames[source]||instruments[source]||source;total.textContent=count.toLocaleString();
  input.onchange=async()=>{if(input.checked)excludedSources.delete(source);else excludedSources.add(source);rebuild(false);try{await estimateProgression('astar')}catch(e){$('metrics').textContent='Calculation failed';$('metrics').title=e.message}};
  label.append(input,name,total);menu.append(label);
 }
}
function setSatelliteMenu(open){$('satelliteMenu').hidden=!open;$('satelliteToggle').setAttribute('aria-expanded',String(open))}
$('satelliteToggle').onclick=()=>setSatelliteMenu($('satelliteMenu').hidden);
document.addEventListener('click',e=>{if(!e.target.closest('.satellite-filter'))setSatelliteMenu(false)});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('satelliteMenu').hidden){setSatelliteMenu(false);$('satelliteToggle').focus()}});
function rebuild(reset=true){stopPlayback();if(progressionActive||progressionRunning)clearProgression();if(coverActive)clearCover();const allRecords=[...selectedEvents.values()].flatMap(e=>e.records);if(reset)renderSatelliteMenu(allRecords);records=allRecords.filter(r=>!excludedSources.has(r.source));$('downloadCsv').disabled=!records.length;if(!records.length){focusTimeRange=null;fullTimeRange=null;updateFocusButton();for(const source of ['spots','latestSpots'])map.getSource(source)?.setData({type:'FeatureCollection',features:[]});bins=[];fluxBins=[];fluxObservations={points:[],peakByCell:new Map(),nominal:0,invalid:0};rosPoints=[];latestIndexedTime=0;latestIndexed.hidden=true;$('metrics').innerHTML='<b>0</b> hotspots';ctx.clearRect(0,0,canvas.width,canvas.height);return}records.sort((a,b)=>a.time-b.time);const first=records[0].time,last=records[records.length-1].time,hour=3600000;start=new Date(first).setMinutes(0,0,0);end=new Date(last).setMinutes(0,0,0);if(end<=last)end+=hour;if(end<=start)end=start+hour;fullTimeRange=[start,end];if(reset)focusTimeRange=null;if(focusTimeRange){start=focusTimeRange[0];end=focusTimeRange[1]}if(reset){$('from').value=0;$('to').value=10000}makeBins();buildTimeSlots();update()}
function downloadCsv(){if(!records.length)return;const rows=['timestamp;instrument;frp;confidence;latitude;longitude',...records.map(r=>{const c=h3.cellToLatLng(r.h3);return`${utcStamp(r.time)};${instruments[r.source]||r.source};${r.frp};${r.confidence};${c[0]};${c[1]}`})],blob=new Blob(['\ufeff'+rows.join('\r\n')+'\r\n'],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`fire-events-${utcStamp(start).slice(0,10)}-${utcStamp(end).slice(0,10)}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function update(){if(!records.length)return;const[a,b]=selected(),visible=records.filter(r=>r.time>=a&&r.time<=b),maxFrp=Math.max(1e-9,...visible.map(r=>r.frp)),logMax=Math.max(1e-9,Math.log1p(maxFrp));updateRangeWindow();updateFocusButton();updateProgressionTime(a,b);$('fromLabel').innerHTML=selectionTime(a);$('timeCaption').textContent='to';$('toLabel').innerHTML=selectionTime(b)+` <small>${selectionZone(a)}</small>`;$('metrics').innerHTML=`<b>${visible.length.toLocaleString()}</b> hotspots`;$('metrics').title=inferredCompactKey();const features=visible.map(r=>{const c=h3.cellToLatLng(r.h3);return{type:'Feature',geometry:{type:'Point',coordinates:[unwrap(c[1]),c[0]]},properties:{frp:r.frp,color:infernoColor(Math.log1p(Math.max(0,r.frp))/logMax),confidence:r.confidence,source:r.source,eventId:r.eventId}}});map.getSource('spots').setData({type:'FeatureCollection',features});latestIndexedTime=Math.max(...records.map(r=>r.time));const latestByCell=Date.now()-latestIndexedTime<latestCrossMaxAge?new Map(records.filter(r=>r.time===latestIndexedTime&&(!focusTimeRange||(r.time>=a&&r.time<=b))).map(r=>[r.h3,r])):new Map();map.getSource('latestSpots')?.setData({type:'FeatureCollection',features:[...latestByCell.values()].map(r=>{const c=h3.cellToLatLng(r.h3);return{type:'Feature',geometry:{type:'Point',coordinates:[unwrap(c[1]),c[0]]},properties:{}}})});renderLatestIndexed();drawChart(a,b)}
const chartSeries={peak:true,mean:true,area:true,viirs:true,ros:true};
function setChartSeriesMenu(open){$('chartSeriesMenu').hidden=!open;$('chartSeriesButton').setAttribute('aria-expanded',String(open))}
function updateChartSeries(){const count=Object.values(chartSeries).filter(Boolean).length;$('chartSeriesButton').dataset.filtered=String(count<5);$('chartSeriesButton').setAttribute('aria-label',`Chart visibility: ${count} of 5 series shown`);if(records.length)drawChart(...selected())}
$('chartSeriesButton').onclick=()=>setChartSeriesMenu($('chartSeriesMenu').hidden);
$('chartSeriesMenu').querySelectorAll('input[data-series]').forEach(input=>input.onchange=()=>{chartSeries[input.dataset.series]=input.checked;updateChartSeries()});
$('chartShowAll').onclick=()=>{$('chartSeriesMenu').querySelectorAll('input[data-series]').forEach(input=>{input.checked=true;chartSeries[input.dataset.series]=true});updateChartSeries()};
document.addEventListener('click',e=>{if(!e.target.closest('.chart-menu-wrap'))setChartSeriesMenu(false)});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('chartSeriesMenu').hidden){setChartSeriesMenu(false);$('chartSeriesButton').focus()}});
function drawChart(a,b){
 const dpr=devicePixelRatio||1,w=canvas.clientWidth,h=canvas.clientHeight;if(canvas.width!==Math.round(w*dpr)||canvas.height!==Math.round(h*dpr)){canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr)}ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);
 const plottedArea=windowArea(progressionArea),plottedViirs=windowArea(viirsArea),plottedROS=rosPoints.filter(p=>p.time>=start&&p.time<=end),shownAreaMax=plottedArea.at(-1)?.area||0,shownViirsMax=plottedViirs.at(-1)?.area||0;
 const pad={l:0,r:0,t:8,b:22},cw=w,ch=h-pad.t-pad.b,n=fluxBins.length||24,span=Math.max(1,end-start),maxDensity=Math.max(1e-9,...fluxBins.map(x=>x.max??0)),maxMean=Math.max(1e-9,...fluxBins.map(x=>x.mean??0)),maxRos=Math.max(0,...plottedROS.map(x=>(x.ros??0)*60)),step=slotStep(),fluxScale=chartSeries.peak?maxDensity:maxMean,areaScale=chartSeries.area?shownAreaMax:shownViirsMax;
 ctx.strokeStyle='#ffffff38';ctx.lineWidth=1;for(let t=start;t<=end;t+=step){const x=(t-start)/span*cw;ctx.beginPath();ctx.moveTo(x,pad.t);ctx.lineTo(x,pad.t+ch);ctx.stroke()}
 if(chartSeries.peak)for(let i=0;i<n;i++){const value=fluxBins[i]?.max;if(value==null)continue;const norm=value/maxDensity,bh=norm*ch,x=i*cw/n,bt=start+(i+.5)/n*span;ctx.globalAlpha=bt>=a&&bt<=b?.85:.24;ctx.fillStyle=infernoColor(norm);ctx.fillRect(x,pad.t+ch-bh,Math.max(1,cw/n+.3),bh)}ctx.globalAlpha=1;
 function drawLine(points,color,scale,width=2){ctx.strokeStyle=color;ctx.lineWidth=width;ctx.beginPath();let previous=false;for(const point of points){if(point.value==null){previous=false;continue}const x=(point.time-start)/span*cw,y=pad.t+ch-point.value/Math.max(1e-9,scale)*ch;previous?ctx.lineTo(x,y):ctx.moveTo(x,y);previous=true}ctx.stroke();ctx.fillStyle=color;points.forEach((point,i)=>{if(point.value!==null&&point.value!==undefined&&points[i-1]?.value==null&&points[i+1]?.value==null){const x=(point.time-start)/span*cw,y=pad.t+ch-point.value/Math.max(1e-9,scale)*ch;ctx.beginPath();ctx.arc(x,y,width/2+1,0,Math.PI*2);ctx.fill()}})}
 if(chartSeries.mean)drawLine(fluxBins.map((x,i)=>({time:start+(i+.5)/n*span,value:x.mean})),'#b44cff',fluxScale);
 if(progressionArea.length){const drawArea=(points,color)=>{ctx.strokeStyle=color;ctx.lineWidth=2.3;ctx.beginPath();let previousY=pad.t+ch-(focusTimeRange?(points[0]?.area||0)/Math.max(1e-9,areaScale)*ch:0);ctx.moveTo(0,previousY);for(const point of points){const x=Math.max(0,Math.min(1,(point.time-start)/span))*cw,y=pad.t+ch-point.area/Math.max(1e-9,areaScale)*ch;ctx.lineTo(x,previousY);ctx.lineTo(x,y);previousY=y}ctx.lineTo(cw,previousY);ctx.stroke()};if(chartSeries.viirs&&viirsArea.length)drawArea(plottedViirs,'#4dabf7');if(chartSeries.area)drawArea(plottedArea,'#ff3636')}
 if(chartSeries.ros){
  // Split segments by estimate maturity; provisional portions stay dashed.
  for(const provisional of [false,true]){
   const points=plottedROS.map(p=>({time:p.time,value:p.warmup===provisional&&p.ros!==null?p.ros*60:null}));
   ctx.setLineDash(provisional?[5,4]:[]);
   drawLine(points,'#080c11',maxRos,4);drawLine(points,'#ffffff',maxRos,2);
  }
  ctx.setLineDash([]);
 }
 const small=w<600;ctx.font=(small?'10':'12')+'px ui-monospace,monospace';let leftY=pad.t+11,rightY=pad.t+11;const visibleLabels=[];
 const legend=(text,color,right=false)=>{ctx.fillStyle=color;ctx.textAlign=right?'right':'left';ctx.fillText(text,right?w-3:2,right?rightY:leftY);if(right)rightY+=15;else leftY+=15;visibleLabels.push(text.replace('ROS max','Rate of spread maximum'))};
 if(chartSeries.peak)legend('Peak '+(maxDensity>1e-9?maxDensity:0).toFixed(3)+' kW·m⁻²'+(fluxObservations.nominal?' ≈':''),'#c2cbd4');
 if(chartSeries.mean)legend('Mean '+(maxMean>1e-9?maxMean:0).toFixed(3)+' kW·m⁻²','#b44cff');
 if(chartSeries.area)legend('Max '+Math.round(shownAreaMax).toLocaleString()+' ha','#ff6666',true);
 if(chartSeries.viirs&&viirsArea.length)legend('VIIRS '+Math.round(shownViirsMax).toLocaleString()+' ha','#74c0fc',true);
 if(chartSeries.ros){
  const established=plottedROS.filter(p=>!p.warmup&&p.ros!==null),provisional=plottedROS.filter(p=>p.warmup&&p.ros!==null);
  legend('ROS max ≈ '+(established.length?Math.max(...established.map(p=>p.ros*60)).toFixed(3):'—')+' m/min','#fff',true);
  if(provisional.length)legend('Provisional max ≈ '+Math.max(...provisional.map(p=>p.ros*60)).toFixed(3)+' m/min · dashed','#c2cbd4',true);
 }
 if(!Object.values(chartSeries).some(Boolean)){ctx.textAlign='center';ctx.fillStyle='#9ca9b6';ctx.fillText('Choose a series in Charts',w/2,pad.t+ch/2)}ctx.textAlign='left';
 canvas.setAttribute('aria-label',(visibleLabels.length?visibleLabels.join('; '):'No chart series shown')+'. Click for calculation details.');
 ctx.font='11px ui-monospace,monospace';ctx.fillStyle='#9ca9b6';ctx.fillText(localStamp(start).slice(0,16),0,pad.t+ch+17);const tail=localStamp(end).slice(0,16),tw=ctx.measureText(tail).width;ctx.fillText(tail,w-tw,pad.t+ch+17)
}
function computeViirsArea(){const cells=new Map();for(const record of records){if(record.source!=='S'&&record.source!=='1'&&record.source!=='2')continue;const cell=h3.cellToParent(record.h3,9),previous=cells.get(cell);if(previous===undefined||record.time<previous)cells.set(cell,record.time)}const areaUnit=h3.UNITS?.m2||'m2',ordered=[...cells].map(([cell,time])=>({time,area:h3.cellArea(cell,areaUnit)/10000})).sort((a,b)=>a.time-b.time);viirsArea=[];viirsMaxArea=0;for(const point of ordered){viirsMaxArea+=point.area;if(viirsArea.length&&viirsArea[viirsArea.length-1].time===point.time)viirsArea[viirsArea.length-1].area=viirsMaxArea;else viirsArea.push({time:point.time,area:viirsMaxArea})}}
async function finishProgression(original,fillers,components,capped,run,method){
 computeViirsArea();
 let t0=Infinity,t1=-Infinity,maxFrp=0;for(const v of original.values()){t0=Math.min(t0,v.time);t1=Math.max(t1,v.time);maxFrp=Math.max(maxFrp,v.frp)}for(const v of fillers.values())maxFrp=Math.max(maxFrp,v.frp);const span=Math.max(1,t1-t0),logFrp=Math.max(1e-9,Math.log1p(maxFrp)),feature=(cell,v,isOriginal)=>{const ring=h3.cellToBoundary(cell,true).map(p=>[unwrap(p[0]),p[1]]);ring.push(ring[0]);return{type:'Feature',geometry:{type:'Polygon',coordinates:[ring]},properties:{cell,time:v.time,frp:v.frp,count:v.count,original:isOriginal?1:0,timeNorm:(v.time-t0)/span,frpNorm:Math.log1p(Math.max(0,v.frp))/logFrp}}},features=[...original].map(([c,v])=>feature(c,v,true)).concat([...fillers].map(([c,v])=>feature(c,v,false)));
 if(run!==progressionGeneration)return;progressionMethod=method;progressionMaxFrp=maxFrp;progressionCells=[...original,...fillers].map(([cell,value])=>[cell,{...value,worldCover:progressionCoverClasses.get(cell)||0}]);if($('downloadBmap'))$('downloadBmap').disabled=!progressionCells.length;isochronesReady=false;const footprintHistory=EventMetrics.areaPerimeterHistory(progressionCells,h3);progressionArea=footprintHistory.map(p=>({time:p.time,area:p.areaM2/10000}));progressionMaxArea=progressionArea.at(-1)?.area||0;rosPoints=EventMetrics.rosSeries(footprintHistory,...(fullTimeRange||[start,end]));map.getSource('progression').setData({type:'FeatureCollection',features});progressionRunning=false;progressionActive=true;$('showProgression').disabled=false;$('showProgression').checked=progressionPreference;$('colorFrp').disabled=false;$('colorFrp').checked=frpColorPreference;$('showIsochrones').disabled=false;$('showIsochrones').checked=isochronePreference;$('progressionAction').disabled=false;$('progressionAction').value='';for(const layer of['progressionFill','progressionLine'])map.setLayoutProperty(layer,'visibility',progressionPreference?'visible':'none');updateProgressionTime(...selected());if(isochronePreference)buildIsochrones();update();const methodName=method==='astar'?'A* constrained':method==='wavecover'?'Wavecover':'Wavefront';$('progressionStatus').textContent=`${methodName} · ${original.size.toLocaleString()} original H9 · ${fillers.size.toLocaleString()} interpolated · ${progressionMaxArea.toLocaleString(undefined,{maximumFractionDigits:0})} ha · ${components.toLocaleString()} groups${capped?' · growth capped':''}`;
}
function astarPath(startCell,goalCell,allowed,maxFillers){
 const maxEdges=maxFillers+1;let direct;try{direct=h3.gridDistance(startCell,goalCell)}catch{return null}if(direct<0||direct>maxEdges)return null;const open=[{cell:startCell,g:0,f:direct}],came=new Map(),best=new Map([[startCell,0]]),closed=new Set();let visited=0;
 while(open.length&&visited++<4000){let at=0;for(let i=1;i<open.length;i++)if(open[i].f<open[at].f)at=i;const current=open.splice(at,1)[0];if(current.cell===goalCell){const path=[goalCell];let cell=goalCell;while(came.has(cell)){cell=came.get(cell);path.push(cell)}return path.reverse()}if(closed.has(current.cell))continue;closed.add(current.cell);let neighbors;try{neighbors=h3.gridDisk(current.cell,1)}catch{continue}for(const next of neighbors){if(next===current.cell||closed.has(next)||(next!==goalCell&&!allowed.has(next)))continue;let heuristic;try{heuristic=h3.gridDistance(next,goalCell)}catch{continue}const g=current.g+1;if(heuristic<0||g+heuristic>maxEdges||g>=(best.get(next)??Infinity))continue;best.set(next,g);came.set(next,current.cell);open.push({cell:next,g,f:g+heuristic})}}
 return null;
}
async function buildAstarProgression(original,run,status){
 const ordered=[...original].map(([cell,v])=>({cell,...v})).sort((a,b)=>a.time-b.time),fillers=new Map();let links=0,holeLinks=0;const timeScale=Math.max(3600000,(ordered[ordered.length-1].time-ordered[0].time)/Math.max(4,Math.sqrt(ordered.length)));
 let allowed;try{allowed=await loadWaveCover(original,run,status,false)}catch(e){status.textContent='A* vegetation mask error: '+e.message;$('progressionAction').disabled=false;$('progressionAction').value='';progressionRunning=false;return}if(!allowed||run!==progressionGeneration)return;
 const addPath=(path,from,to)=>{const added=[],support=Math.min(5,(from.support??from.count??0)+(to.support??to.count??0));for(let k=1;k<path.length-1;k++){const cell=path[k];if(original.has(cell))continue;const f=k/(path.length-1),value={time:from.time+(to.time-from.time)*f,frp:from.frp+(to.frp-from.frp)*f,count:0,support},old=fillers.get(cell);if(!old){fillers.set(cell,value);added.push(cell)}else{old.support=Math.max(old.support||0,support);if(value.time<old.time){old.time=value.time;old.frp=value.frp}}}return added};
 for(let i=1;i<ordered.length;i++){let best=null;for(let j=Math.max(0,i-24);j<i;j++){let distance;try{distance=h3.gridDistance(ordered[j].cell,ordered[i].cell)}catch{continue}if(distance<1||distance>6)continue;const score=distance+2*(ordered[i].time-ordered[j].time)/timeScale;if(!best||score<best.score)best={from:ordered[j],score}}if(!best)continue;const to=ordered[i],path=astarPath(best.from.cell,to.cell,allowed,5);if(!path)continue;links++;addPath(path,best.from,to);if(i%100===0){status.textContent=`A* local temporal paths… ${i.toLocaleString()} / ${ordered.length.toLocaleString()}`;await new Promise(requestAnimationFrame);if(run!==progressionGeneration)return}}
 const anchors=new Map(ordered.map(v=>[v.cell,{...v,support:v.count}]));for(const[cell,v]of fillers)anchors.set(cell,{cell,...v});const seenBridges=new Set();for(let pass=1;pass<=1;pass++){const snapshot=[...anchors.values()],newAnchors=[];for(let i=0;i<snapshot.length;i++){const from=snapshot[i];let nearby;try{nearby=h3.gridDisk(from.cell,7)}catch{continue}for(const cell of nearby){if(cell<=from.cell||!anchors.has(cell))continue;const pair=from.cell+'|'+cell;if(seenBridges.has(pair))continue;seenBridges.add(pair);const to=anchors.get(cell);if((from.support||0)+(to.support||0)<5)continue;const path=astarPath(from.cell,to.cell,allowed,6);if(!path||path.length<3)continue;const added=addPath(path,from.time<=to.time?from:to,from.time<=to.time?to:from);if(!added.length)continue;holeLinks++;for(const addedCell of added)newAnchors.push({cell:addedCell,...fillers.get(addedCell)})}if(i%100===0){status.textContent=`Filling vegetation holes · ${i.toLocaleString()} / ${snapshot.length.toLocaleString()}`;await new Promise(requestAnimationFrame);if(run!==progressionGeneration)return}}for(const value of newAnchors)anchors.set(value.cell,value);if(!newAnchors.length)break}
 status.textContent=`Rendering ${links.toLocaleString()} local paths + ${holeLinks.toLocaleString()} hole bridges…`;await finishProgression(original,fillers,Math.max(1,ordered.length-links-holeLinks),false,run,'astar');
}
async function estimateProgression(method='wavefront'){
 if(progressionActive)clearProgression();if(records.length<2)return;await mapReady;const run=++progressionGeneration,status=$('progressionStatus');progressionCoverClasses.clear();progressionRunning=true;if($('downloadBmap'))$('downloadBmap').disabled=true;$('progressionAction').disabled=true;status.hidden=false;status.textContent='Aggregating original H9 cells…';
 const original=new Map();for(const r of records){const cell=h3.cellToParent(r.h3,9),v=original.get(cell);if(v){v.time=Math.min(v.time,r.time);v.frp=fluxObservations.peakByCell.get(cell)||0;v.count++}else original.set(cell,{time:r.time,frp:fluxObservations.peakByCell.get(cell)||0,count:1})}if(original.size<2){status.textContent='Progression requires at least two original H9 cells';$('progressionAction').disabled=false;$('progressionAction').value='';progressionRunning=false;return}if(method==='astar'){await buildAstarProgression(original,run,status);return}let coverMask=null;if(method==='wavecover')try{coverMask=await loadWaveCover(original,run,status)}catch(e){status.textContent='Wavecover error: '+e.message;$('progressionAction').disabled=false;$('progressionAction').value='';progressionRunning=false;return}if(method==='wavecover'&&!coverMask)return;
 const seeds=[...original.keys()],owner=new Map(),distance=new Map(),parent=new Map(),queue=[],roots=new Map(seeds.map(x=>[x,x]));let components=seeds.length,qi=0,visited=seeds.length,capped=false;for(const seed of seeds){owner.set(seed,seed);distance.set(seed,0);parent.set(seed,null);queue.push(seed)}const find=x=>{let r=x;while(roots.get(r)!==r)r=roots.get(r);while(roots.get(x)!==x){const n=roots.get(x);roots.set(x,r);x=n}return r},join=(a,b)=>{a=find(a);b=find(b);if(a===b)return false;roots.set(b,a);components--;return true},connections=[],seenPairs=new Set(),MAX_RADIUS=80,MAX_VISITED=250000;
 while(qi<queue.length&&visited<MAX_VISITED&&components>1){const cell=queue[qi++],d=distance.get(cell);if(d>=MAX_RADIUS)continue;let neighbors;try{neighbors=h3.gridDisk(cell,1)}catch{continue}for(const next of neighbors){if(next===cell)continue;if(!owner.has(next)){if(coverMask&&!coverMask.has(next))continue;owner.set(next,owner.get(cell));distance.set(next,d+1);parent.set(next,cell);queue.push(next);visited++;if(visited>=MAX_VISITED)break}else if(owner.get(next)!==owner.get(cell)){const a=owner.get(cell),b=owner.get(next),key=a<b?a+'|'+b:b+'|'+a;if(!seenPairs.has(key)){seenPairs.add(key);connections.push({a:cell,b:next,oa:a,ob:b});join(a,b)}}}if(qi%4000===0){status.textContent=`${coverMask?'Growing vegetation wavefront':'Growing H9 fronts'}… ${visited.toLocaleString()} cells`;await new Promise(requestAnimationFrame);if(run!==progressionGeneration)return}}if(visited>=MAX_VISITED)capped=true;status.textContent=coverMask?'Filling connected vegetation territories…':'Filling connected wavefront territories…';await new Promise(requestAnimationFrame);const partners=new Map(),addPartner=(a,b,length)=>{if(!partners.has(a))partners.set(a,new Map());const old=partners.get(a).get(b);if(old===undefined||length<old)partners.get(a).set(b,length)};for(const link of connections){const length=distance.get(link.a)+1+distance.get(link.b);addPartner(link.oa,link.ob,length);addPartner(link.ob,link.oa,length)}const fillers=new Map(),FILL_MARGIN=12;let fillCount=0;
 for(const[cell,oa]of owner){if(original.has(cell)||!partners.has(oa)||(coverMask&&!coverMask.has(cell)))continue;const dA=distance.get(cell);let ob=null,dB=Infinity,bestScore=Infinity;for(const[candidate,length]of partners.get(oa)){let d;try{d=h3.gridDistance(cell,candidate)}catch{continue}const score=dA+d-length;if(d>=0&&score<=FILL_MARGIN&&score<bestScore){dB=d;ob=candidate;bestScore=score}}if(!ob)continue;const A=original.get(oa),B=original.get(ob),f=dA/Math.max(1,dA+dB);fillers.set(cell,{time:A.time+(B.time-A.time)*f,frp:A.frp+(B.frp-A.frp)*f,count:0});if(++fillCount%5000===0){status.textContent=`Filling gaps… ${fillCount.toLocaleString()} H9 cells`;await new Promise(requestAnimationFrame);if(run!==progressionGeneration)return}}await finishProgression(original,fillers,components,capped,run,method==='wavecover'?'wavecover':'wavefront');
}
async function fetchEvent(eventId){if(selectedEvents.has(eventId))return selectedEvents.get(eventId);const d=await eventData(eventId),color=colorFor(eventId),event={...d,color,records:d.records.map(x=>({...x,eventId,color,time:tixEpoch(x.tix),frp:Number.isFinite(x.frp)&&x.frp>=0?x.frp:null})).sort((a,b)=>a.time-b.time)};selectedEvents.set(eventId,event);return event}
async function toggleEvent(eventId,checked,input){input.disabled=true;try{if(checked)await fetchEvent(eventId);else selectedEvents.delete(eventId);rebuild();await estimateProgression('astar')}catch(e){input.checked=!checked;$('nearbyList').prepend(Object.assign(document.createElement('div'),{className:'error',textContent:e.message}))}finally{input.disabled=eventId===primaryId}}
function updateSelectAll(){const selectable=nearbyEvents.filter(e=>e.id!==primaryId);$('selectAll').textContent=selectable.length&&selectable.every(e=>selectedEvents.has(e.id))?'Deselect all':'Select all';$('selectAll').disabled=!selectable.length}
let historyHover=-1,nearbySelectionDirty=false;
function historySquare(event,id){const center=h3.cellToLatLng(event.h7),boundary=h3.cellToBoundary(event.h7),base=Math.max(.0005,...boundary.map(point=>Math.abs(point[0]-center[0])))*1.12*(id===historyHover?2:1),longitude=unwrap(center[1]),longitudeRadius=base/Math.max(.15,Math.cos(center[0]*Math.PI/180)),ring=[[longitude-longitudeRadius,center[0]-base],[longitude+longitudeRadius,center[0]-base],[longitude+longitudeRadius,center[0]+base],[longitude-longitudeRadius,center[0]+base],[longitude-longitudeRadius,center[0]-base]];return{id,type:'Feature',geometry:{type:'Polygon',coordinates:[ring]},properties:{color:colorFor(event.id)}}}
function updateHistoryLayers(){const markers=nearbyEvents.map((event,id)=>({event,id})).filter(x=>!selectedEvents.has(x.event.id)).map(({event,id})=>historySquare(event,id)),selected=[...selectedEvents].filter(([id])=>id!==primaryId).flatMap(([id,event])=>event.records.filter(record=>!focusTimeRange||(record.time>=start&&record.time<=end)).map(record=>{const c=h3.cellToLatLng(record.h3);return{type:'Feature',geometry:{type:'Point',coordinates:[unwrap(c[1]),c[0]]},properties:{color:colorFor(id)}}}));map.getSource('historyEvents')?.setData({type:'FeatureCollection',features:markers});map.getSource('historySelected')?.setData({type:'FeatureCollection',features:selected})}
function setNearbyDirty(dirty){nearbySelectionDirty=dirty;$('nearbyApply').disabled=!dirty}
async function toggleHistoryEvent(eventId,checked,input){input.disabled=true;try{if(checked)await fetchEvent(eventId);else selectedEvents.delete(eventId);setNearbyDirty(true);updateHistoryLayers()}catch(e){input.checked=!checked;$('nearbyList').prepend(Object.assign(document.createElement('div'),{className:'error',textContent:e.message}))}finally{input.disabled=false}}
async function applyNearbySelection(){if(!nearbySelectionDirty)return;const button=$('nearbyApply');button.disabled=true;button.textContent='Applying…';try{rebuild();await estimateProgression('astar');setNearbyDirty(false);updateHistoryLayers()}catch(e){$('nearbyList').prepend(Object.assign(document.createElement('div'),{className:'error',textContent:e.message}));button.disabled=false}finally{button.textContent='Apply'}}
function renderNearby(){const list=$('nearbyList');list.innerHTML=nearbyEvents.length?nearbyEvents.map((event,index)=>{const color=colorFor(event.id),checked=selectedEvents.has(event.id),date=stamp(tixEpoch(event.last)).slice(0,10);return`<label class="nearby-row" data-feature="${index}"><input type="checkbox" data-id="${event.id.replaceAll('&','&amp;').replaceAll('"','&quot;')}" ${checked?'checked':''} ${event.id===primaryId?'disabled':''}><span class="swatch" style="background:${color}"></span><span class="event-meta"><b>${date} · ${Math.round(event.frp).toLocaleString()} FRP · ${event.hotspots.toLocaleString()} Pt.</b><a class="event-link" href="${eventPage(event.id)}">Open</a></span></label>`}).join(''):'No archive events';list.querySelectorAll('input[data-id]').forEach(input=>input.onchange=()=>toggleHistoryEvent(input.dataset.id,input.checked,input));list.querySelectorAll('.nearby-row').forEach(row=>{const id=+row.dataset.feature;row.onmouseenter=()=>{historyHover=id;updateHistoryLayers()};row.onmouseleave=()=>{historyHover=-1;updateHistoryLayers()}});updateHistoryLayers()}
function updateSearchArea(){const features=[...searchH5].map(cell=>{const ring=h3.cellToBoundary(cell,true).map(p=>[unwrap(p[0]),p[1]]);ring.push(ring[0]);return{type:'Feature',geometry:{type:'Polygon',coordinates:[ring]},properties:{h5:cell}}});map.getSource('searchArea')?.setData({type:'FeatureCollection',features});$('searchCount').textContent=`${searchH5.size.toLocaleString()} H5 cells`}
async function loadNearby(){if(!primaryH5)return;if(!searchH5.size)searchH5=new Set(h3.gridDisk(primaryH5,1));updateSearchArea();$('nearbyList').textContent='Loading nearby events…';try{nearbyEvents=await eventList(new URLSearchParams({api:'nearby_events',h5:[...searchH5].join(','),sort:$('nearbySort').value}));renderNearby()}catch(e){$('nearbyList').textContent=e.message}}
function eventH6Cells(event){return new Set(event.records.map(r=>h3.cellToParent(r.h3,6)))}
function expandedH6(cells,radius){if(!radius)return cells;const expanded=new Set(cells);for(const cell of cells)for(const neighbor of h3.gridDisk(cell,radius))expanded.add(neighbor);return expanded}
async function autoSelectNearby(primary){const h5s=h3.gridDisk(primaryH5,1);if(!searchH5.size)searchH5=new Set(h5s);try{nearbyEvents=await eventList(new URLSearchParams({api:'nearby_events',h5:h5s.join(','),sort:$('nearbySort').value}));const first=tixL23(primary.records[0].tix)-1n,last=tixL23(primary.records[primary.records.length-1].tix)+1n,candidates=nearbyEvents.filter(e=>e.id!==primaryId&&tixL23(e.last)>=first&&tixL23(e.first)<=last),loaded=[];await concurrentMap(candidates,4,async e=>loaded.push(await fetchEvent(e.id)));for(const event of loaded)selectedEvents.delete(event.id);const footprint=eventH6Cells(primary);let total=primary.records.length,pending=loaded;while(pending.length){const radius=total>=10000?2:total>=500?1:0,reachable=expandedH6(footprint,radius),next=[],accepted=[];for(const event of pending)([...eventH6Cells(event)].some(cell=>reachable.has(cell))?accepted:next).push(event);if(!accepted.length)break;for(const event of accepted){selectedEvents.set(event.id,event);total+=event.records.length;for(const cell of eventH6Cells(event))footprint.add(cell)}pending=next}setNearbyDirty(false);renderNearby()}catch(e){$('nearbyList').textContent='Automatic nearby selection failed: '+e.message}}
async function growSearch(){const grown=new Set(searchH5);for(const cell of searchH5)for(const neighbor of h3.gridDisk(cell,1))grown.add(neighbor);searchH5=grown;updateSearchArea();await loadNearby()}
async function loadHistory(){if(!searchH5.size)searchH5=new Set(h3.gridDisk(primaryH5,1));for(let pass=0;pass<2;pass++){const grown=new Set(searchH5);for(const cell of searchH5)for(const neighbor of h3.gridDisk(cell,1))grown.add(neighbor);searchH5=grown}updateSearchArea();await loadNearby();const coordinates=[...searchH5].flatMap(cell=>h3.cellToBoundary(cell,true).map(p=>[unwrap(p[0]),p[1]]));if(coordinates.length){const bounds=coordinates.reduce((box,c)=>box.extend(c),new maplibregl.LngLatBounds(coordinates[0],coordinates[0]));map.fitBounds(bounds,{padding:{top:90,bottom:290,left:40,right:Math.min(480,innerWidth*.35)},maxZoom:8,duration:500})}}
function hideHistory(){map.getSource('searchArea')?.setData({type:'FeatureCollection',features:[]});map.getSource('historyEvents')?.setData({type:'FeatureCollection',features:[]});map.getSource('historySelected')?.setData({type:'FeatureCollection',features:[]})}
async function selectAllNearby(){const others=nearbyEvents.filter(e=>e.id!==primaryId),all=others.length&&others.every(e=>selectedEvents.has(e.id));$('selectAll').disabled=true;if(all){others.forEach(e=>selectedEvents.delete(e.id));rebuild();renderNearby();return}const missing=others.filter(e=>!selectedEvents.has(e.id));let next=0,done=0;const worker=async()=>{while(next<missing.length){const e=missing[next++];await fetchEvent(e.id);$('selectAll').textContent=`Loading ${++done}/${missing.length}`}};try{await Promise.all(Array.from({length:Math.min(4,missing.length)},worker));rebuild();renderNearby()}catch(e){$('nearbyList').prepend(Object.assign(document.createElement('div'),{className:'error',textContent:e.message}));renderNearby()}}
function eventState(){const q=new URLSearchParams(params),c=map.getCenter(),extra=[...selectedEvents.keys()].filter(x=>x!==primaryId);q.set('id',primaryId);if(extra.length)q.set('events',extra.join(','));else q.delete('events');if(searchH5.size)q.set('search',[...searchH5].join(','));else q.delete('search');q.set('ev_lng',c.lng.toFixed(5));q.set('ev_lat',c.lat.toFixed(5));q.set('ev_z',map.getZoom().toFixed(2));q.set('ev_bearing',map.getBearing().toFixed(1));q.set('ev_pitch',map.getPitch().toFixed(1));q.set('ev_tf',$('from').value);q.set('ev_tt',$('to').value);q.set('basemap',$('basemap').value);q.set('nearby',$('nearby').hidden?'0':'1');q.set('nearby_sort',$('nearbySort').value);q.set('progression',progressionActive?'1':'0');q.set('progression_method',progressionMethod);q.set('cover',coverActive?'1':'0');q.set('show_hotspots',$('showHotspots').checked?'1':'0');q.set('color_instrument',$('colorInstrument').checked?'1':'0');q.set('local_time',$('localTime').checked?'1':'0');q.set('show_progression',$('showProgression').checked?'1':'0');q.set('color_frp',$('colorFrp').checked?'1':'0');q.set('isochrones',$('showIsochrones').checked?'1':'0');return q}
async function copyUrl(url,button,label){try{await navigator.clipboard.writeText(url);button.textContent='Copied';setTimeout(()=>button.textContent=label,1400)}catch{prompt(label,url)}}
function inferredCompactKey(){return canonicalKey||(primaryId||'').split('/').pop()?.replace(/\.stfy$/,'')||''}
function shareEvent(){const key=inferredCompactKey();if(key)copyUrl(location.origin+location.pathname+'?'+key,$('share'),'Share')}
function trackEvent(){const key=inferredCompactKey();if(key)window.open('https://certec.mtg.eebe.upc.edu/fet-eurowest/viewer/?stfy='+encodeURIComponent(key),'_blank','noopener')}
function shareView(){copyUrl(location.origin+location.pathname+'?'+eventState(),$('shareView'),'Copy same view')}
async function resolveCompact(){const r=await fetch('stfyhotspot.php?'+new URLSearchParams({api:'resolve',key:compactKey,db:database})),d=await r.json();if(!r.ok||d.error)throw Error(d.error||`HTTP ${r.status}`);primaryId=d.id;database=d.database;canonicalKey=d.key;params.set('id',primaryId);params.set('db',database);if(d.merged&&canonicalKey!==compactKey)history.replaceState(null,'','?'+canonicalKey)}
async function load(){try{if(compactKey)await resolveCompact();if(!primaryId)throw Error('Missing event id');$('track').disabled=!inferredCompactKey();const d=await fetchEvent(primaryId);if(!d.records.length)throw Error('Empty event');anchorLng=h3.cellToLatLng(d.records[0].h3)[1];primaryH5=h3.cellToParent(d.records[0].h3,5);clusterDateTitle=titleDate(tixEpoch(d.records[0].tix));setClusterTitle();const center=eventCenter(d);inferRegionName(center.lat,center.lng).then(setClusterTitle).catch(()=>{});searchH5=new Set();await mapReady;await autoSelectNearby(d);if($('nearby').hidden)hideHistory();rebuild();if(!params.has('ev_lng')){const coords=records.map(x=>h3.cellToLatLng(x.h3)).map(c=>[unwrap(c[1]),c[0]]),bounds=coords.reduce((box,c)=>box.extend(c),new maplibregl.LngLatBounds(coords[0],coords[0]));map.fitBounds(bounds,{padding:{top:90,bottom:40,left:40,right:40},maxZoom:11,duration:0})}await estimateProgression('astar')}catch(e){$('metrics').textContent=e.message;$('metrics').className='metrics error'}}
let playbackFrame=0,playbackLast=0,playbackAtEnd=false,rangeDrag=null;function stopPlayback(){if(playbackFrame)cancelAnimationFrame(playbackFrame);playbackFrame=0;playbackLast=0;playbackAtEnd=false;$('timelinePlay').textContent='▶';$('timelinePlay').setAttribute('aria-label','Play timeline');$('timelinePlay').setAttribute('aria-pressed','false');$('timelinePlay').title='Play timeline'}function playbackTick(now){if(!playbackFrame)return;if(!playbackLast)playbackLast=now;const elapsed=now-playbackLast;if(elapsed>=50){playbackLast=now;let a=+$('from').value,b=+$('to').value;if(a>b)[a,b]=[b,a];const width=Math.max(1,b-a),limit=10000-width;if(playbackAtEnd){a=0;playbackAtEnd=false}else{a=Math.min(limit,a+elapsed);if(a>=limit)playbackAtEnd=true}$('from').value=Math.round(a);$('to').value=Math.round(a+width);update()}playbackFrame=requestAnimationFrame(playbackTick)}function startPlayback(){let a=+$('from').value,b=+$('to').value;if(a>b)[a,b]=[b,a];if(b-a>=10000){const width=Math.max(1,Math.round(10000/(bins[0]?.values.length||24)));$('from').value=0;$('to').value=width;update()}$('timelinePlay').textContent='❚❚';$('timelinePlay').setAttribute('aria-label','Pause timeline');$('timelinePlay').setAttribute('aria-pressed','true');$('timelinePlay').title='Pause timeline';playbackLast=0;playbackFrame=requestAnimationFrame(playbackTick)}$('timelinePlay').onclick=()=>playbackFrame?stopPlayback():startPlayback();$('rangeWindow').onpointerdown=e=>{stopPlayback();e.preventDefault();let a=+$('from').value,b=+$('to').value;if(a>b)[a,b]=[b,a];rangeDrag={x:e.clientX,a,b,id:e.pointerId};$('rangeWindow').setPointerCapture(e.pointerId)};$('rangeWindow').onpointermove=e=>{if(!rangeDrag||e.pointerId!==rangeDrag.id)return;const width=rangeDrag.b-rangeDrag.a,delta=Math.round((e.clientX-rangeDrag.x)/$('sliders').clientWidth*10000),a=Math.max(0,Math.min(10000-width,rangeDrag.a+delta));$('from').value=a;$('to').value=a+width;update()};const endRangeDrag=e=>{if(rangeDrag&&e.pointerId===rangeDrag.id)rangeDrag=null};$('rangeWindow').onpointerup=endRangeDrag;$('rangeWindow').onpointercancel=endRangeDrag;$('from').onpointerdown=stopPlayback;$('to').onpointerdown=stopPlayback;
function applyBasemap(value){$('basemap').value=value;const satellite=value==='satellite';map.setLayoutProperty('satellite','visibility',satellite?'visible':'none');map.setLayoutProperty('base','visibility',satellite?'none':'visible');for(const button of document.querySelectorAll('[data-basemap]'))button.setAttribute('aria-pressed',String(button.dataset.basemap===value))}
$('nearbyButton').textContent='Around';$('nearbyApply').onclick=applyNearbySelection;
for(const button of document.querySelectorAll('[data-basemap]')){button.setAttribute('aria-pressed',String(button.dataset.basemap===$('basemap').value));button.onclick=()=>applyBasemap(button.dataset.basemap);}$('basemap').onchange=()=>applyBasemap($('basemap').value);$('showHotspots').onchange=()=>map.getLayer('spots')&&map.setLayoutProperty('spots','visibility',$('showHotspots').checked?'visible':'none');$('colorInstrument').onchange=update;$('localTime').onchange=()=>{$('timeCaption').textContent=$('localTime').checked?'Local Start - Local End':'UTC Start - UTC End';if(records.length)update();renderNearby()};$('showProgression').onchange=()=>{progressionPreference=$('showProgression').checked;map.getLayer('progressionFill')&&map.setLayoutProperty('progressionFill','visibility',progressionPreference?'visible':'none');update()};$('colorFrp').onchange=()=>{frpColorPreference=$('colorFrp').checked;updateProgressionTime(...selected());drawChart(...selected())};$('showIsochrones').onchange=()=>{isochronePreference=$('showIsochrones').checked;if(isochronePreference){map.setLayoutProperty('isochroneLines','visibility','visible');buildIsochrones()}else map.setLayoutProperty('isochroneLines','visibility','none')};$('nearbyButton').onclick=async()=>{$('nearby').hidden=!$('nearby').hidden;if(!$('nearby').hidden)await loadHistory();else hideHistory()};$('nearbyClose').onclick=()=>{$('nearby').hidden=true;hideHistory()};$('growSearch').onclick=growSearch;$('selectAll').onclick=selectAllNearby;$('nearbySort').onchange=loadNearby;$('coverButton').onclick=loadCoverMetadata;$('progressionAction').onchange=()=>{const action=$('progressionAction').value;if(action==='clear')clearProgression();else if(action)estimateProgression(action)};$('creditsButton').onclick=()=>$('credits').showModal();$('creditsClose').onclick=()=>$('credits').close();$('credits').onclick=e=>{if(e.target===$('credits'))$('credits').close()};$('downloadCsv').onclick=downloadCsv;$('moreButton').onclick=toggleMoreMenu;$('share').onclick=shareEvent;$('track').onclick=trackEvent;$('shareView').onclick=shareView;$('from').oninput=update;$('to').oninput=update;addEventListener('resize',()=>records.length&&drawChart(...selected()));loadLatestIndexed().catch(()=>latestIndexed.textContent='Latest indexed: unavailable');load();

function analysisUrl(){
 const q=new URLSearchParams({id:primaryId,db:database,events:[...selectedEvents.keys()].filter(id=>id!==primaryId).join(','),selection:'explicit',key:inferredCompactKey(),excluded_sources:[...excludedSources].join(',')});
 const [a,b]=selected();q.set('from_ms',String(a));q.set('to_ms',String(b));return 'analysis.html?'+q;
}
function toggleMoreMenu(){const open=$('moreMenu').hidden;$('moreMenu').hidden=!open;$('moreButton').setAttribute('aria-expanded',String(open));if(open)$('aerialBasemap').focus()}
document.addEventListener('click',e=>{if(!e.target.closest('.more-menu')){$('moreMenu').hidden=true;$('moreButton').setAttribute('aria-expanded','false')}});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('moreMenu').hidden){$('moreMenu').hidden=true;$('moreButton').setAttribute('aria-expanded','false');$('moreButton').focus()}});

$('chart').onclick=()=>$('chartMethod').showModal();$('chart').onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();$('chartMethod').showModal()}};$('chartMethodClose').onclick=()=>$('chartMethod').close();$('chartMethod').onclick=e=>{if(e.target===$('chartMethod'))$('chartMethod').close()};

$('timelineFocus').onclick=toggleTimeFocus;

// More menu actions retain their original handlers after moving into the dropdown.
function closeMoreMenu(){ $('moreMenu').hidden=true; $('moreButton').setAttribute('aria-expanded','false'); }
$('moreMenu').addEventListener('click',event=>{
 const action=event.target.closest('a,button');
 if(action&&!action.disabled){closeMoreMenu();if(!document.querySelector('dialog[open]'))$('moreButton').focus()}
});
$('helpButton').onclick=()=>{$('eventHelp').showModal();$('eventHelp').scrollTop=0};
$('helpClose').onclick=()=>$('eventHelp').close();
$('eventHelp').onclick=e=>{if(e.target===$('eventHelp'))$('eventHelp').close()};
for(const id of ['eventHelp','credits'])$(id).addEventListener('close',()=>$('moreButton').focus());
let bmapNoticeTimer=0;
function bmapNotice(message){clearTimeout(bmapNoticeTimer);$('bmapNotice').textContent=message;$('bmapNotice').hidden=false;bmapNoticeTimer=setTimeout(()=>$('bmapNotice').hidden=true,8000)}
if($('downloadBmap'))$('downloadBmap').onclick=()=>{
 if(progressionRunning||!progressionActive||!progressionCells.length)return;
 try{
  const buffer=EventBmap.encode(progressionCells),url=URL.createObjectURL(new Blob([buffer],{type:'application/octet-stream'})),link=document.createElement('a');
  link.href=url;link.download=(inferredCompactKey()||'event').replace(/[^a-zA-Z0-9_-]/g,'_')+'.bmap';
  document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);
  const unknown=progressionCells.filter(([,v])=>!v.worldCover).length;
  bmapNotice(`Downloaded ${progressionCells.length.toLocaleString()} H9 hexes`+(unknown?` · ${unknown.toLocaleString()} with unknown WorldCover (0)`:'')+'.');
 }catch(error){bmapNotice('BMAP download failed: '+error.message)}
};
